const fs = require('fs');
const path = require('path');

const rawPredictionCsv = `2026-03-21 00:00:00,0.964,0.984
2026-03-21 01:00:00,1.058,0.977
2026-03-21 02:00:00,1.012,0.968
2026-03-21 03:00:00,1.028,0.977
2026-03-21 04:00:00,0.957,0.980
2026-03-21 05:00:00,1.020,1.036
2026-03-21 06:00:00,1.030,1.035
2026-03-21 07:00:00,1.062,1.049
2026-03-21 08:00:00,1.212,1.128
2026-03-21 09:00:00,1.133,1.142
2026-03-21 10:00:00,1.086,1.184
2026-03-21 11:00:00,1.257,1.205
2026-03-21 12:00:00,1.256,1.192
2026-03-21 13:00:00,1.224,1.204
2026-03-21 14:00:00,1.148,1.218
2026-03-21 15:00:00,1.091,1.183
2026-03-21 16:00:00,0.992,1.068
2026-03-21 17:00:00,1.218,1.122
2026-03-21 18:00:00,1.088,1.185
2026-03-21 19:00:00,1.176,1.178
2026-03-21 20:00:00,1.229,1.141
2026-03-21 21:00:00,1.176,1.132
2026-03-21 22:00:00,1.006,0.968
2026-03-21 23:00:00,1.065,0.956`;

const predictionData = rawPredictionCsv.split('\n').map(line => {
  const [time, actual, predicted] = line.split(',');
  const hour = time.split(' ')[1].substring(0, 5);
  return {
    label: hour,
    actual: parseFloat(actual),
    predicted: parseFloat(predicted)
  };
});

const powerBalanceData = [];
for (let h = 0; h < 24; h++) {
  let pv = 0;
  if (h >= 6 && h <= 18) {
    const sun = Math.max(0, Math.sin(Math.PI * (h - 6) / 12));
    pv = 0.95 * sun * (1 - 0.05 * Math.random());
  }
  
  const load = predictionData[h].actual;
  
  powerBalanceData.push({
    label: (h < 10 ? '0' + h : h.toString()) + ':00',
    pv: parseFloat(pv.toFixed(3)),
    load: parseFloat(load.toFixed(3))
  });
}

const fileContent = "// GENERATED BY scripts/parse_data.js\n" +
"// Synthetic Machine Learning & Telemetry Data for UI Presentations\n\n" +
"export const predictionData = " + JSON.stringify(predictionData, null, 2) + ";\n\n" +
"export const powerBalanceData = " + JSON.stringify(powerBalanceData, null, 2) + ";\n";

const outPath = path.join(__dirname, '../src/data/simulatedData.ts');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, fileContent, 'utf-8');

console.log('Successfully generated simulated data at src/data/simulatedData.ts');
