// GENERATED BY scripts/parse_data.js
// Synthetic Machine Learning & Telemetry Data for UI Presentations

export const predictionData = [
  {
    "label": "00:00",
    "actual": 0.964,
    "predicted": 0.984
  },
  {
    "label": "01:00",
    "actual": 1.058,
    "predicted": 0.977
  },
  {
    "label": "02:00",
    "actual": 1.012,
    "predicted": 0.968
  },
  {
    "label": "03:00",
    "actual": 1.028,
    "predicted": 0.977
  },
  {
    "label": "04:00",
    "actual": 0.957,
    "predicted": 0.98
  },
  {
    "label": "05:00",
    "actual": 1.02,
    "predicted": 1.036
  },
  {
    "label": "06:00",
    "actual": 1.03,
    "predicted": 1.035
  },
  {
    "label": "07:00",
    "actual": 1.062,
    "predicted": 1.049
  },
  {
    "label": "08:00",
    "actual": 1.212,
    "predicted": 1.128
  },
  {
    "label": "09:00",
    "actual": 1.133,
    "predicted": 1.142
  },
  {
    "label": "10:00",
    "actual": 1.086,
    "predicted": 1.184
  },
  {
    "label": "11:00",
    "actual": 1.257,
    "predicted": 1.205
  },
  {
    "label": "12:00",
    "actual": 1.256,
    "predicted": 1.192
  },
  {
    "label": "13:00",
    "actual": 1.224,
    "predicted": 1.204
  },
  {
    "label": "14:00",
    "actual": 1.148,
    "predicted": 1.218
  },
  {
    "label": "15:00",
    "actual": 1.091,
    "predicted": 1.183
  },
  {
    "label": "16:00",
    "actual": 0.992,
    "predicted": 1.068
  },
  {
    "label": "17:00",
    "actual": 1.218,
    "predicted": 1.122
  },
  {
    "label": "18:00",
    "actual": 1.088,
    "predicted": 1.185
  },
  {
    "label": "19:00",
    "actual": 1.176,
    "predicted": 1.178
  },
  {
    "label": "20:00",
    "actual": 1.229,
    "predicted": 1.141
  },
  {
    "label": "21:00",
    "actual": 1.176,
    "predicted": 1.132
  },
  {
    "label": "22:00",
    "actual": 1.006,
    "predicted": 0.968
  },
  {
    "label": "23:00",
    "actual": 1.065,
    "predicted": 0.956
  }
];

export const powerBalanceData = [
  {
    "label": "00:00",
    "pv": 0,
    "load": 0.964
  },
  {
    "label": "01:00",
    "pv": 0,
    "load": 1.058
  },
  {
    "label": "02:00",
    "pv": 0,
    "load": 1.012
  },
  {
    "label": "03:00",
    "pv": 0,
    "load": 1.028
  },
  {
    "label": "04:00",
    "pv": 0,
    "load": 0.957
  },
  {
    "label": "05:00",
    "pv": 0,
    "load": 1.02
  },
  {
    "label": "06:00",
    "pv": 0,
    "load": 1.03
  },
  {
    "label": "07:00",
    "pv": 0.243,
    "load": 1.062
  },
  {
    "label": "08:00",
    "pv": 0.458,
    "load": 1.212
  },
  {
    "label": "09:00",
    "pv": 0.645,
    "load": 1.133
  },
  {
    "label": "10:00",
    "pv": 0.823,
    "load": 1.086
  },
  {
    "label": "11:00",
    "pv": 0.906,
    "load": 1.257
  },
  {
    "label": "12:00",
    "pv": 0.919,
    "load": 1.256
  },
  {
    "label": "13:00",
    "pv": 0.873,
    "load": 1.224
  },
  {
    "label": "14:00",
    "pv": 0.784,
    "load": 1.148
  },
  {
    "label": "15:00",
    "pv": 0.666,
    "load": 1.091
  },
  {
    "label": "16:00",
    "pv": 0.473,
    "load": 0.992
  },
  {
    "label": "17:00",
    "pv": 0.235,
    "load": 1.218
  },
  {
    "label": "18:00",
    "pv": 0,
    "load": 1.088
  },
  {
    "label": "19:00",
    "pv": 0,
    "load": 1.176
  },
  {
    "label": "20:00",
    "pv": 0,
    "load": 1.229
  },
  {
    "label": "21:00",
    "pv": 0,
    "load": 1.176
  },
  {
    "label": "22:00",
    "pv": 0,
    "load": 1.006
  },
  {
    "label": "23:00",
    "pv": 0,
    "load": 1.065
  }
];
